name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  mix_test:
    name: mix test (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})

    strategy:
      matrix:
        include:
          - elixir: 1.13.4
            otp: 24.3

          - elixir: 1.15.4
            otp: 25.3
            lint: lint

          - elixir: 1.16.3
            otp: 26.2
            lint: lint

          # update coverage report as well
          - elixir: 1.17.2
            otp: 27.0
            lint: lint

    runs-on: ubuntu-latest

    steps:
    - name: Install inotify-tools
      run: |
        sudo apt update
        sudo apt install -y inotify-tools
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps and _build cache
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install dependencies
      run: mix deps.get --only test

    #- name: Check source code format
    #  run: mix format --check-formatted
    #  if: ${{ matrix.lint }}

    - name: Remove compiled application files
      run: mix clean

    - name: Compile dependencies
      run: mix compile
      if: ${{ !matrix.lint }}
      env:
        MIX_ENV: test

    - name: Compile & lint dependencies
      run: mix compile --warnings-as-errors
      if: ${{ matrix.lint }}
      env:
        MIX_ENV: test

    - name: Run tests
      run: mix test --cover --export-coverage default

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mix-test-coverage-${{ matrix.otp }}-${{ matrix.elixir }}
        path: cover/default.coverdata
        retention-days: 7

  npm_test:
    name: npm test

    strategy:
      matrix:
        include:
          - elixir: 1.17.2
            otp: 27.0

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore deps and _build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install and test
        run: npm run js:test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: js-unit-coverage
          path: assets/coverage/
          retention-days: 7

  e2e_test:
    name: e2e test

    strategy:
      matrix:
        include:
          - elixir: 1.17.2
            otp: 27.0

    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    env:
      ImageOS: ubuntu22
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install unzip
        run: apt update && apt -y install unzip

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore deps and _build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Install dependencies
        run: mix deps.get

      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: setup
        run: npm run setup

      - name: Run e2e tests
        run: npm run e2e:test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: test/e2e/test-results/
          retention-days: 7
        
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mix-e2e-coverage
          path: cover/e2e.coverdata
          retention-days: 7

  coverage_report:
    name: coverage report

    runs-on: ubuntu-latest
    needs: [mix_test, npm_test, e2e_test]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.17.2
          otp-version: 27.0

      - name: Download mix unit coverage
        uses: actions/download-artifact@v4
        with:
          # This needs to be updated when changing the test matrix
          name: mix-test-coverage-27-1.17.2
          path: cover/

      - name: Download mix e2e coverage
        uses: actions/download-artifact@v4
        with:
          name: mix-e2e-coverage
          path: cover/

      - name: Restore deps and _build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-27-1.17.2-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-27-1.17.2

      - name: Generate mix coverage report
        run: mix test.coverage

      - name: Download js-unit-coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: js-unit-coverage
          path: assets/coverage/

      - name: Download e2e-test-results artifact
        uses: actions/download-artifact@v4
        with:
          name: e2e-test-results
          path: test/e2e/test-results/

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Merge coverage reports
        run: npm install && npm run cover:merge

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: overall-coverage
          path: cover/
          retention-days: 7
